export const communityFeedData = [
    {
      id: 1,
      user: 'Alice',
      title: 'Fitness Bootcamp',
      description: 'Start your day strong! Join the bootcamp at 6 am in Hall A.',
      date: '12-05-2025',
      time: '06:00',
      userSrc: '/images/iconly/members/alice.svg',
    },
    {
      id: 2,
      user: 'Bob',
      title: 'HIIT Session',
      description: 'Intense 45-minute HIIT workout with Coach Jake.',
      date: '13-05-2025',
      time: '07:30',
      userSrc: '/images/iconly/members/bob.svg',
    },
    {
      id: 3,
      user: 'Charlie',
      title: 'Yoga & Stretching',
      description: 'Improve flexibility with a guided yoga session.',
      date: '14-05-2025',
      time: '08:00',
      userSrc: '/images/iconly/members/charlie.svg',
    },
    {
      id: 4,
      user: 'Diana',
      title: 'Zumba Dance',
      description: 'Burn calories with fun Zumba moves!',
      date: '14-05-2025',
      time: '18:00',
      userSrc: '/images/iconly/members/diana.svg',
    },
    {
      id: 5,
      user: 'Ethan',
      title: 'Weightlifting Basics',
      description: 'Intro class on form and technique in weightlifting.',
      date: '15-05-2025',
      time: '09:00',
      userSrc: '/images/iconly/members/ethan.svg',
    },
    {
      id: 6,
      user: 'Fiona',
      title: 'Spin Class',
      description: '30-minute spin for cardio endurance.',
      date: '15-05-2025',
      time: '17:00',
      userSrc: '/images/iconly/members/fiona.svg',
    },
    {
      id: 7,
      user: 'George',
      title: 'CrossFit Challenge',
      description: 'Test your limits with today’s CrossFit WOD.',
      date: '16-05-2025',
      time: '06:30',
      userSrc: '/images/iconly/members/george.svg',
    },
    {
      id: 8,
      user: 'Hannah',
      title: 'Pilates Core Session',
      description: 'Strengthen your core and posture in Studio B.',
      date: '16-05-2025',
      time: '08:30',
      userSrc: '/images/iconly/members/hannah.svg',
    },
    {
      id: 9,
      user: 'Ivan',
      title: 'Functional Training',
      description: 'Train for strength, balance, and mobility.',
      date: '17-05-2025',
      time: '07:00',
      userSrc: '/images/iconly/members/ivan.svg',
    },
    {
      id: 10,
      user: 'Julia',
      title: 'Evening Meditation',
      description: 'Relax your body and mind with guided meditation.',
      date: '17-05-2025',
      time: '19:00',
      userSrc: '/images/iconly/members/julia.svg',
    },
  ];
  