export const leadssData = [
  {
    id: '1',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for 3 months membership',
  },
  {
    id: '2',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Trial',
  },
  {
    id: '3',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '4',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Trial',
  },
  {
    id: '5',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for 3 months membership',
  },
  {
    id: '6',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    subscriptionType: 'Basic',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Trial',
  },
  {
    id: '7',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    subscriptionType: 'Basic',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for 3 months membership',
  },
  {
    id: '8',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Trial',
  },
  {
    id: '9',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for 3 months membership',
  },
  {
    id: '10',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for 1 months membership',
  },
  {
    id: '11',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for 6 months membership',
  },
  {
    id: '12',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '13',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '14',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '15',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '16',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '17',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for gym',
  },
  {
    id: '18',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for 12 months membership',
  },
  {
    id: '19',
    name: 'Mike',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Contacted',
    address: '10 Downing Street',
    goal: 'Inquiry for 1 months membership',
  },
  {
    id: '20',
    name: 'John',
    gender: 'Male',
    mobileNumber: '+91 1234567890',
    email: 'mike@email.com',
    status: 'Pending',
    address: '10 Downing Street',
    goal: 'Inquiry for 12 months membership',
  },
];

export const leadStatusData = [
  {
    value: 'NEW',
    label: 'New'
  },
  {
    value: 'CONTACTED',
    label: 'Contacted'
  },
  {
    value: 'FOLLOW_UP',
    label: 'Follow Up'
  },
  {
    value: 'CONVERTED',
    label: 'Converted'
  },
  {
    value: 'LOST',
    label: 'Lost'
  }
]